# File is used by the openapi-generator cli to generate a python client.
generatorName: python
gitUserId: hashicorp
gitRepoId: nomad-openapi/clients/python/v1
inputSpec: /local/v1/openapi.yaml
outputDir: /local/clients/python/v1
packageName: nomad_client
packageVersion: 1.1.4